name: my_self_work_project
description: "my_self_work_project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  firebase_core: ^3.4.0 #Firebase의 필수 기반 기능
  firebase_auth: ^5.0.0 #Firebase 인증
  provider: ^6.0.0 #상태 관리 도구
  http: ^0.13.6   #HTTP 통신 라이브러리(REST API 호출)
  lottie: ^2.7.0 #애니메이션

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/ai_generating.json
  uses-material-design: true